import { Student, Teacher, Class, Payment, Attendance, Notification, UserRole } from "@/types";

export const MOCK_STUDENTS = [
  {
    id: "s1",
    user_id: "u1",
    full_name: "Nguyễn Anh Tuấn",
    email: "tuan.nva@gmail.com",
    dob: "2008-03-15",
    school: "THPT Nguyễn Thị Minh Khai",
    grade: "Lớp 12",
    learning_type: "hybrid" as const,
    parent_id: "p1",
    avatar_url: null,
    created_at: "2024-09-01",
  },
  {
    id: "s2",
    user_id: "u2",
    full_name: "Trần Mai Phương",
    email: "phuong.tm@gmail.com",
    dob: "2009-07-22",
    school: "THPT Lê Quý Đôn",
    grade: "Lớp 10",
    learning_type: "online" as const,
    parent_id: "p2",
    avatar_url: null,
    created_at: "2024-09-01",
  },
  {
    id: "s3",
    user_id: "u3",
    full_name: "Lê Hoàng Đức",
    email: "duc.lh@gmail.com",
    dob: "2011-01-08",
    school: "THPT Trần Phú",
    grade: "Lớp 10",
    learning_type: "offline" as const,
    parent_id: "p3",
    avatar_url: null,
    created_at: "2024-09-01",
  },
  {
    id: "s4",
    user_id: "u4",
    full_name: "Phạm Thảo My",
    email: "my.pt@gmail.com",
    dob: "2010-11-30",
    school: "THCS Nguyễn Du",
    grade: "Lớp 8",
    learning_type: "hybrid" as const,
    parent_id: "p1",
    avatar_url: null,
    created_at: "2024-09-01",
  },
  {
    id: "s5",
    user_id: "u5",
    full_name: "Vũ Nhật Nam",
    email: "nam.vn@gmail.com",
    dob: "2009-05-14",
    school: "THPT Lê Quý Đôn",
    grade: "Lớp 10",
    learning_type: "online" as const,
    parent_id: "p4",
    avatar_url: null,
    created_at: "2024-09-01",
  },
];

export const MOCK_PARENTS = [
  { id: "p1", user_id: "pu1", full_name: "Trần Văn Minh",  email: "minh.tv@gmail.com",  phone: "0903111222", avatar_url: null, created_at: "2024-09-01" },
  { id: "p2", user_id: "pu2", full_name: "Trần Thị Hoa",   email: "hoa.tt@gmail.com",   phone: "0903222333", avatar_url: null, created_at: "2024-09-01" },
  { id: "p3", user_id: "pu3", full_name: "Lê Quốc Bảo",    email: "bao.lq@gmail.com",   phone: "0903333444", avatar_url: null, created_at: "2024-09-01" },
  { id: "p4", user_id: "pu4", full_name: "Vũ Thanh Hằng",  email: "hang.vt@gmail.com",  phone: "0903444555", avatar_url: null, created_at: "2024-09-01" },
];

export const MOCK_TEACHERS = [
  {
    id: "t1",
    user_id: "tu1",
    full_name: "Thầy Hùng Toán",
    specialization: "Toán Đại Số & Luyện Thi",
    avatar_url: null,
    bio: "10 năm kinh nghiệm chuyên luyện thi Đại học khối A, A1.",
    created_at: "2024-08-01",
  },
  {
    id: "t2",
    user_id: "tu2",
    full_name: "Cô Lan Anh",
    specialization: "Toán Hình Học",
    avatar_url: null,
    bio: "Đam mê truyền cảm hứng học Hình học không gian cho học sinh THPT.",
    created_at: "2024-08-01",
  },
  {
    id: "t3",
    user_id: "tu3",
    full_name: "Thầy Minh Trí",
    specialization: "Toán Olympic & Nâng Cao",
    avatar_url: null,
    bio: "Cựu học sinh chuyên Toán, chuyên bồi dưỡng học sinh giỏi Toán cấp Quốc gia.",
    created_at: "2024-08-01",
  },
];

export const MOCK_CLASSES = [
  {
    id: "c1",
    class_name: "Toán Nâng Cao 12",
    subject: "Toán học",
    grade: 12,
    learning_mode: "hybrid" as const,
    tutor_id: "t1",
    classroom: "Phòng 201",
    zoom_link: "https://zoom.us/j/123456789",
    schedule: [
      { day: "Monday", start_time: "18:00", end_time: "19:30" },
      { day: "Wednesday", start_time: "18:00", end_time: "19:30" },
    ],
    description: "Đại số, Tích phân và Hình học không gian chuẩn bị cho kỳ thi THPT Quốc Gia.",
    max_students: 15,
    student_ids: ["s1", "s2", "s4"],
    color: "#6366f1",
    created_at: "2024-09-01",
  },
  {
    id: "c2",
    class_name: "Chuyên đề Hình Học 11",
    subject: "Toán học",
    grade: 11,
    learning_mode: "offline" as const,
    tutor_id: "t2",
    classroom: "Phòng 105",
    schedule: [
      { day: "Tuesday", start_time: "19:30", end_time: "21:00" },
      { day: "Thursday", start_time: "19:30", end_time: "21:00" },
    ],
    description: "Lấy gốc và học sâu Hình học không gian, vectơ trong không gian.",
    max_students: 12,
    student_ids: ["s1", "s5"],
    color: "#f59e0b",
    created_at: "2024-09-01",
  },
  {
    id: "c3",
    class_name: "Toán Đại Số 10 Cơ Bản",
    subject: "Toán học",
    grade: 10,
    learning_mode: "online" as const,
    tutor_id: "t1",
    zoom_link: "https://zoom.us/j/987654321",
    schedule: [
      { day: "Wednesday", start_time: "19:30", end_time: "21:00" },
      { day: "Friday", start_time: "19:30", end_time: "21:00" },
    ],
    description: "Củng cố kiến thức nền tảng Đại số lớp 10, phương trình, hệ phương trình.",
    max_students: 20,
    student_ids: ["s2", "s3"],
    color: "#10b981",
    created_at: "2024-09-01",
  },
  {
    id: "c4",
    class_name: "Đội Tuyển Olympic Toán 9",
    subject: "Toán học",
    grade: 9,
    learning_mode: "offline" as const,
    tutor_id: "t3",
    classroom: "Phòng 301",
    zoom_link: "https://zoom.us/j/456789123",
    schedule: [
      { day: "Saturday", start_time: "14:00", end_time: "17:00" },
    ],
    description: "Bồi dưỡng chuyên sâu Số học, Tổ hợp, Bất đẳng thức dành cho học sinh giỏi thi chuyên.",
    max_students: 8,
    student_ids: ["s3", "s4"],
    color: "#ec4899",
    created_at: "2024-09-01",
  },
];

export const MOCK_CLASS_MATERIALS = [
  {
    id: "mat1",
    class_id: "c1",
    title: "Bộ công thức Đạo hàm & Tích phân",
    description: "Tổng hợp đầy đủ các công thức cần nhớ cho chương Đạo hàm và Nguyên hàm - Tích phân.",
    file_url: "/uploads/cong-thuc-dao-ham.pdf",
    file_type: "pdf",
    file_size: "2.4 MB",
    uploaded_by: "t1",
    created_at: "2025-04-15T10:00:00Z",
    download_count: 45,
    category: "formula" as const,
  },
  {
    id: "mat2",
    class_id: "c1",
    title: "Đề cương ôn tập Giữa kỳ 2",
    description: "Đề cương chi tiết bao gồm các dạng bài trọng tâm và câu hỏi tự luyện.",
    file_url: "/uploads/de-cuong-giua-ky.pdf",
    file_type: "pdf",
    file_size: "1.8 MB",
    uploaded_by: "t1",
    created_at: "2025-04-20T14:30:00Z",
    download_count: 38,
    category: "exam_prep" as const,
  },
  {
    id: "mat3",
    class_id: "c1",
    title: "Bảng tóm tắt Hàm số & Đồ thị",
    description: "Infographic tóm tắt các dạng đồ thị hàm số bậc 3, bậc 4 và phân thức.",
    file_url: "/uploads/tom-tat-ham-so.png",
    file_type: "image",
    file_size: "4.2 MB",
    uploaded_by: "t1",
    created_at: "2025-05-01T09:00:00Z",
    download_count: 62,
    category: "summary" as const,
  },
  {
    id: "mat4",
    class_id: "c2",
    title: "Tài liệu Hình học không gian Oxyz",
    description: "File bài tập và lý thuyết chương Hình học tọa độ trong không gian.",
    file_url: "/uploads/hinh-hoc-oxyz.pdf",
    file_type: "pdf",
    file_size: "3.1 MB",
    uploaded_by: "t2",
    created_at: "2025-04-25T11:00:00Z",
    download_count: 28,
    category: "textbook" as const,
  },
  {
    id: "mat5",
    class_id: "c2",
    title: "Bộ đề thi thử Hình học",
    description: "10 đề thi thử trắc nghiệm chương Hình học không gian có đáp án chi tiết.",
    file_url: "/uploads/de-thi-thu-hinh-hoc.pdf",
    file_type: "pdf",
    file_size: "5.6 MB",
    uploaded_by: "t2",
    created_at: "2025-05-05T16:00:00Z",
    download_count: 55,
    category: "exam_prep" as const,
  },
  {
    id: "mat6",
    class_id: "c3",
    title: "Sơ đồ tư duy Phương trình bậc 2",
    description: "Mindmap hệ thống hóa kiến thức phương trình bậc 2, tam thức bậc 2.",
    file_url: "/uploads/so-do-tu-duy-pt2.png",
    file_type: "image",
    file_size: "2.8 MB",
    uploaded_by: "t1",
    created_at: "2025-05-02T08:00:00Z",
    download_count: 34,
    category: "summary" as const,
  },
  {
    id: "mat7",
    class_id: "c4",
    title: "Đề thi Olympic Toán các năm",
    description: "Tuyển tập đề thi Olympic Toán cấp thành phố và quốc gia từ 2018-2024.",
    file_url: "/uploads/olympic-math.pdf",
    file_type: "pdf",
    file_size: "8.4 MB",
    uploaded_by: "t3",
    created_at: "2025-04-10T13:00:00Z",
    download_count: 72,
    category: "exam_prep" as const,
  },
];

export const MOCK_LECTURES = [
  {
    id: "lec1",
    class_id: "c1",
    title: "Chương 1: Ứng dụng Đạo hàm",
    description: "Tìm cực trị hàm số, GTLN-GTNN, tiếp tuyến, tiệm cận. Bao gồm phân tích bài tập mẫu SGK.",
    video_url: "https://example.com/lecture1.mp4",
    duration: "1 giờ 25 phút",
    order: 1,
    uploaded_by: "t1",
    created_at: "2025-03-10T10:00:00Z",
    views: 128,
    is_published: true,
    slides_url: "/uploads/slides-ch1.pdf",
  },
  {
    id: "lec2",
    class_id: "c1",
    title: "Chương 2: Nguyên hàm - Tích phân",
    description: "Phương pháp tính nguyên hàm, tích phân xác định, ứng dụng tính diện tích hình phẳng.",
    video_url: "https://example.com/lecture2.mp4",
    duration: "1 giờ 30 phút",
    order: 2,
    uploaded_by: "t1",
    created_at: "2025-03-17T10:00:00Z",
    views: 112,
    is_published: true,
    slides_url: "/uploads/slides-ch2.pdf",
  },
  {
    id: "lec3",
    class_id: "c1",
    title: "Chương 3: Số phức",
    description: "Khái niệm số phức, các phép toán, biểu diễn hình học, phương trình trên tập số phức.",
    video_url: "https://example.com/lecture3.mp4",
    duration: "1 giờ 15 phút",
    order: 3,
    uploaded_by: "t1",
    created_at: "2025-03-24T10:00:00Z",
    views: 95,
    is_published: true,
    slides_url: "/uploads/slides-ch3.pdf",
  },
  {
    id: "lec4",
    class_id: "c1",
    title: "Chương 4: Khảo sát hàm số (Nâng cao)",
    description: "Các dạng bài khảo sát hàm số vận dụng cao, đồ thị hàm số chứa tham số.",
    video_url: null,
    duration: "Chưa xác định",
    order: 4,
    uploaded_by: "t1",
    created_at: "2025-04-01T10:00:00Z",
    views: 0,
    is_published: false,
    slides_url: null,
  },
  {
    id: "lec5",
    class_id: "c2",
    title: "Bài 1: Vectơ trong không gian",
    description: "Khái niệm vectơ, tích vô hướng, tích có hướng, ứng dụng trong hình học không gian.",
    video_url: "https://example.com/lecture5.mp4",
    duration: "1 giờ 20 phút",
    order: 1,
    uploaded_by: "t2",
    created_at: "2025-03-12T19:30:00Z",
    views: 87,
    is_published: true,
    slides_url: "/uploads/slides-vec.pdf",
  },
  {
    id: "lec6",
    class_id: "c2",
    title: "Bài 2: Phương trình mặt phẳng",
    description: "Cách viết phương trình mặt phẳng, khoảng cách điểm-mặt phẳng, góc giữa các mặt phẳng.",
    video_url: "https://example.com/lecture6.mp4",
    duration: "1 giờ 10 phút",
    order: 2,
    uploaded_by: "t2",
    created_at: "2025-03-19T19:30:00Z",
    views: 74,
    is_published: true,
    slides_url: "/uploads/slides-mp.pdf",
  },
  {
    id: "lec7",
    class_id: "c4",
    title: "Phương pháp giải BĐT - Phần 1",
    description: "Bất đẳng thức AM-GM, Cauchy-Schwarz, phương pháp SOS, Schur.",
    video_url: "https://example.com/lecture7.mp4",
    duration: "2 giờ 30 phút",
    order: 1,
    uploaded_by: "t3",
    created_at: "2025-03-15T14:00:00Z",
    views: 156,
    is_published: true,
    slides_url: "/uploads/slides-bdt.pdf",
  },
];

export const MOCK_CLASS_NOTES = [
  {
    id: "note1",
    class_id: "c1",
    title: "Lưu ý quan trọng: Công thức tích phân từng phần",
    content: "Các em nhớ: ∫u·dv = u·v - ∫v·du. Khi chọn u, ưu tiên theo thứ tự: L-I-A-T-E (Logarithm → Inverse trig → Algebraic → Trig → Exponential). Nếu tích phân quay vòng thì đặt I = tích phân ban đầu rồi giải phương trình.",
    is_pinned: true,
    uploaded_by: "t1",
    created_at: "2025-05-05T18:30:00Z",
    updated_at: "2025-05-05T18:30:00Z",
    tags: ["tích phân", "quan trọng"],
  },
  {
    id: "note2",
    class_id: "c1",
    title: "Thông báo: Đổi lịch học tuần tới",
    content: "Do trùng lịch thi giữa kỳ, buổi học thứ 4 (ngày 14/05) sẽ được dời sang thứ 6 (ngày 16/05) cùng khung giờ 18:00-19:30. Link Zoom giữ nguyên.",
    is_pinned: true,
    uploaded_by: "t1",
    created_at: "2025-05-10T09:00:00Z",
    updated_at: "2025-05-10T09:00:00Z",
    tags: ["lịch học", "thông báo"],
  },
  {
    id: "note3",
    class_id: "c1",
    title: "Mẹo giải nhanh trắc nghiệm Hàm số",
    content: "Dạng 1: Tìm m để hàm số có cực trị → Δ' > 0.\nDạng 2: Số giao điểm đồ thị → Số nghiệm phương trình hoành độ giao.\nDạng 3: GTLN-GTNN trên đoạn → So sánh giá trị tại cực trị và 2 đầu mút.\n\nCác em luyện thêm 20 câu trong file đính kèm nhé!",
    is_pinned: false,
    uploaded_by: "t1",
    created_at: "2025-05-08T20:15:00Z",
    updated_at: "2025-05-08T20:15:00Z",
    tags: ["mẹo giải", "trắc nghiệm"],
  },
  {
    id: "note4",
    class_id: "c1",
    title: "Kết quả thi giữa kỳ",
    content: "Điểm thi giữa kỳ đã có trên hệ thống. Nhìn chung lớp làm tốt, điểm TB lớp 8.2/10. Bạn nào dưới 7 điểm liên hệ thầy để được bổ trợ thêm. Buổi sau thầy sẽ chữa đề thi.",
    is_pinned: false,
    uploaded_by: "t1",
    created_at: "2025-05-03T15:00:00Z",
    updated_at: "2025-05-03T15:00:00Z",
    tags: ["điểm thi", "kết quả"],
  },
  {
    id: "note5",
    class_id: "c2",
    title: "Phương pháp dựng hình không gian",
    content: "Khi gặp bài toán hình không gian:\n1. Đọc kỹ giả thiết, xác định các yếu tố đã cho.\n2. Vẽ hình 3D → đánh dấu các đại lượng.\n3. Xác định mặt phẳng cần tìm khoảng cách.\n4. Dựng đường vuông góc → tam giác vuông.\n\nLưu ý: Luôn kiểm tra điều kiện vuông góc trước khi tính.",
    is_pinned: true,
    uploaded_by: "t2",
    created_at: "2025-05-06T20:00:00Z",
    updated_at: "2025-05-06T20:00:00Z",
    tags: ["hình không gian", "phương pháp"],
  },
  {
    id: "note6",
    class_id: "c4",
    title: "Tài liệu tham khảo thêm",
    content: "Ngoài giáo trình chính, các em có thể tham khảo thêm:\n- \"Problems from the Book\" - Titu Andreescu\n- \"Inequalities\" - Hardy, Littlewood, Polya\n- Kho đề thi AMC/AIME trên Art of Problem Solving\n\nThầy sẽ giao thêm bài từ các nguồn này.",
    is_pinned: false,
    uploaded_by: "t3",
    created_at: "2025-04-20T14:00:00Z",
    updated_at: "2025-04-20T14:00:00Z",
    tags: ["tài liệu tham khảo"],
  },
];

export const MOCK_ATTENDANCE = [
  // s2 (Trần Mai Phương) — class c1 (Thứ Hai & Thứ Tư)
  { id: "a2",  class_id: "c1", student_id: "s2", attendance_date: "2026-06-01", status: "present" as const },
  { id: "a2b", class_id: "c1", student_id: "s2", attendance_date: "2026-06-03", status: "late"    as const },
  { id: "a2c", class_id: "c1", student_id: "s2", attendance_date: "2026-06-08", status: "present" as const },
  { id: "a2d", class_id: "c1", student_id: "s2", attendance_date: "2026-06-10", status: "absent"  as const },
  { id: "a2e", class_id: "c1", student_id: "s2", attendance_date: "2026-06-15", status: "present" as const },
  { id: "a2f", class_id: "c1", student_id: "s2", attendance_date: "2026-06-17", status: "present" as const },
  { id: "a2g", class_id: "c1", student_id: "s2", attendance_date: "2026-06-22", status: "late"    as const },
  { id: "a2h", class_id: "c1", student_id: "s2", attendance_date: "2026-06-24", status: "present" as const },
  // s2 — class c3 (Thứ Tư & Thứ Sáu)
  { id: "a7",  class_id: "c3", student_id: "s2", attendance_date: "2026-06-03", status: "present" as const },
  { id: "a7b", class_id: "c3", student_id: "s2", attendance_date: "2026-06-05", status: "present" as const },
  { id: "a7c", class_id: "c3", student_id: "s2", attendance_date: "2026-06-10", status: "late"    as const },
  { id: "a7d", class_id: "c3", student_id: "s2", attendance_date: "2026-06-12", status: "present" as const },
  { id: "a7e", class_id: "c3", student_id: "s2", attendance_date: "2026-06-17", status: "present" as const },
  { id: "a7f", class_id: "c3", student_id: "s2", attendance_date: "2026-06-19", status: "excused" as const },
  { id: "a7g", class_id: "c3", student_id: "s2", attendance_date: "2026-06-24", status: "present" as const },
  { id: "a7h", class_id: "c3", student_id: "s2", attendance_date: "2026-06-26", status: "present" as const },
  // s3 (Lê Hoàng Đức) — class c3 (Thứ Tư & Thứ Sáu)
  { id: "a8",  class_id: "c3", student_id: "s3", attendance_date: "2026-06-03", status: "present" as const },
  { id: "a8b", class_id: "c3", student_id: "s3", attendance_date: "2026-06-05", status: "absent"  as const },
  { id: "a8c", class_id: "c3", student_id: "s3", attendance_date: "2026-06-10", status: "present" as const },
  { id: "a8d", class_id: "c3", student_id: "s3", attendance_date: "2026-06-12", status: "present" as const },
  { id: "a8e", class_id: "c3", student_id: "s3", attendance_date: "2026-06-17", status: "late"    as const },
  { id: "a8f", class_id: "c3", student_id: "s3", attendance_date: "2026-06-19", status: "present" as const },
  { id: "a8g", class_id: "c3", student_id: "s3", attendance_date: "2026-06-24", status: "present" as const },
  { id: "a8h", class_id: "c3", student_id: "s3", attendance_date: "2026-06-26", status: "absent"  as const },
  // s4 (Phạm Thảo My) — class c1 (Thứ Hai & Thứ Tư)
  { id: "a4",  class_id: "c1", student_id: "s4", attendance_date: "2026-06-01", status: "present" as const },
  { id: "a4b", class_id: "c1", student_id: "s4", attendance_date: "2026-06-03", status: "present" as const },
  { id: "a4c", class_id: "c1", student_id: "s4", attendance_date: "2026-06-08", status: "present" as const },
  { id: "a4d", class_id: "c1", student_id: "s4", attendance_date: "2026-06-10", status: "late"    as const },
  { id: "a4e", class_id: "c1", student_id: "s4", attendance_date: "2026-06-15", status: "absent"  as const },
  { id: "a4f", class_id: "c1", student_id: "s4", attendance_date: "2026-06-17", status: "present" as const },
  { id: "a4g", class_id: "c1", student_id: "s4", attendance_date: "2026-06-22", status: "present" as const },
  { id: "a4h", class_id: "c1", student_id: "s4", attendance_date: "2026-06-24", status: "present" as const },
  // s1 — class c1 (Thứ Hai & Thứ Tư each week)
  { id: "a10", class_id: "c1", student_id: "s1", attendance_date: "2026-06-01", status: "present" as const },
  { id: "a11", class_id: "c1", student_id: "s1", attendance_date: "2026-06-03", status: "present" as const },
  { id: "a12", class_id: "c1", student_id: "s1", attendance_date: "2026-06-08", status: "late"    as const },
  { id: "a13", class_id: "c1", student_id: "s1", attendance_date: "2026-06-10", status: "present" as const },
  { id: "a14", class_id: "c1", student_id: "s1", attendance_date: "2026-06-15", status: "present" as const },
  { id: "a15", class_id: "c1", student_id: "s1", attendance_date: "2026-06-17", status: "absent"  as const },
  { id: "a16", class_id: "c1", student_id: "s1", attendance_date: "2026-06-22", status: "present" as const },
  { id: "a17", class_id: "c1", student_id: "s1", attendance_date: "2026-06-24", status: "present" as const },
  // s1 — class c2 (Thứ Ba each week)
  { id: "a20", class_id: "c2", student_id: "s1", attendance_date: "2026-06-02", status: "present" as const },
  { id: "a21", class_id: "c2", student_id: "s1", attendance_date: "2026-06-09", status: "present" as const },
  { id: "a22", class_id: "c2", student_id: "s1", attendance_date: "2026-06-16", status: "late"    as const },
  { id: "a23", class_id: "c2", student_id: "s1", attendance_date: "2026-06-23", status: "present" as const },
  // Other students — class c2
  { id: "a6",  class_id: "c2", student_id: "s5", attendance_date: "2026-06-02", status: "present" as const },
];

export const MOCK_HOMEWORK = [
  {
    id: "h1",
    class_id: "c1",
    title: "Chương 2: Đạo hàm và Tích phân",
    description: "Hoàn thành các bài tập từ 2.1 đến 2.15 SGK. Chú ý trình bày rõ ràng các bước giải.",
    due_date: "2026-07-15",
    created_at: "2026-07-01",
  },
  {
    id: "h2",
    class_id: "c2",
    title: "Khoảng cách trong không gian",
    description: "Giải 5 bài tập về tính khoảng cách từ điểm đến mặt phẳng đính kèm trong file PDF.",
    due_date: "2026-07-10",
    created_at: "2026-07-01",
  },
  {
    id: "h3",
    class_id: "c4",
    title: "Đề luyện Bất Đẳng Thức Cauchy",
    description: "Nộp lời giải chi tiết cho 10 bài Bất đẳng thức đề cương số 4.",
    due_date: "2026-07-20",
    created_at: "2026-07-02",
  },
  {
    id: "h4",
    class_id: "c1",
    title: "Trắc nghiệm: Hàm số",
    description: "Hoàn thành 50 câu trắc nghiệm cực trị và đồ thị hàm số.",
    due_date: "2026-07-05",
    created_at: "2026-06-28",
  },
];

export const MOCK_SUBMISSIONS = [
  {
    id: "sub1",
    homework_id: "h1",
    student_id: "s1",
    file_url: "/uploads/tuan_math.pdf",
    score: 9.2,
    feedback: "Em làm bài rất tốt! Lời giải rõ ràng, lập luận chặt chẽ. Cần chú ý thêm ở bài 2.14 tính toán sai dấu ở dòng cuối.",
    submitted_at: "2025-05-08",
    status: "graded" as const,
  },
  {
    id: "sub2",
    homework_id: "h2",
    student_id: "s2",
    file_url: "/uploads/phuong_geometry.pdf",
    score: 8.8,
    feedback: "Khá tốt. Em vẽ hình đẹp, tuy nhiên việc dựng đường cao phụ ở bài 3 hơi rườm rà.",
    submitted_at: "2025-05-10",
    status: "graded" as const,
  },
  {
    id: "sub3",
    homework_id: "h3",
    student_id: "s3",
    file_url: null,
    score: null,
    feedback: null,
    submitted_at: null,
    status: "submitted" as const,
  },
  // s2 — nộp h1 (c1), chưa nộp h4 (c1)
  {
    id: "sub4",
    homework_id: "h1",
    student_id: "s2",
    file_url: "/uploads/phuong_calculus.pdf",
    score: 7.5,
    feedback: "Em trình bày được các ý chính, tuy nhiên bài 2.9 và 2.12 còn thiếu bước trung gian. Cần rèn luyện thêm phần lập luận.",
    submitted_at: "2026-06-20",
    status: "graded" as const,
  },
  // s4 — nộp h1 và h4 (c1), đều được chấm
  {
    id: "sub5",
    homework_id: "h1",
    student_id: "s4",
    file_url: "/uploads/thao_my_calculus.pdf",
    score: 9.5,
    feedback: "Xuất sắc! Trình bày rõ ràng, logic chặt chẽ. Bài 2.14 em xử lý rất khéo, đúng cách.",
    submitted_at: "2026-06-18",
    status: "graded" as const,
  },
  {
    id: "sub6",
    homework_id: "h4",
    student_id: "s4",
    file_url: "/uploads/thao_my_trac_nghiem.pdf",
    score: 9.0,
    feedback: "Đạt 45/50 câu. Chú ý các câu về cực trị hàm hợp, em còn nhầm dấu ở một vài chỗ.",
    submitted_at: "2026-07-03",
    status: "graded" as const,
  },
];

export const MOCK_PAYMENTS = [
  { id: "pay1", student_id: "s1", amount: 1500000, due_date: "2025-05-01", paid_date: "2025-04-28", payment_status: "paid" as const, description: "Học phí Tháng 5" },
  { id: "pay2", student_id: "s2", amount: 1200000, due_date: "2025-05-01", paid_date: null, payment_status: "overdue" as const, description: "Học phí Tháng 5" },
  { id: "pay3", student_id: "s3", amount: 1200000, due_date: "2025-06-01", paid_date: null, payment_status: "pending" as const, description: "Học phí Tháng 6" },
  { id: "pay4", student_id: "s4", amount: 1500000, due_date: "2025-05-01", paid_date: "2025-05-01", payment_status: "paid" as const, description: "Học phí Tháng 5" },
  { id: "pay5", student_id: "s5", amount: 1000000, due_date: "2025-05-01", paid_date: "2025-04-30", payment_status: "paid" as const, description: "Học phí Tháng 5" },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "n1", title: "Bài tập Toán mới", content: "Chương 2: Đạo hàm và Tích phân đã được giao trong lớp Toán Nâng Cao 12. Hạn chót: 10/05.", target_role: "student" as const, is_read: false, created_at: "2025-05-03T10:00:00Z" },
  { id: "n2", title: "Thông báo Điểm danh", content: "Em Hoàng Đức đã vắng mặt trong buổi học Toán Hình Học 11 hôm nay.", target_role: "parent" as const, is_read: false, created_at: "2025-05-05T09:30:00Z" },
  { id: "n3", title: "Nhắc nhở Học phí", content: "Học phí môn Toán tháng 5/2025 đã quá hạn. Vui lòng thanh toán sớm.", target_role: "parent" as const, is_read: true, created_at: "2025-05-02T08:00:00Z" },
  { id: "n4", title: "Bài tập đã được chấm", content: "Bài tập chương 2 của em đã được Thầy Hùng chấm. Điểm: 9.2/10.", target_role: "student" as const, is_read: false, created_at: "2025-05-11T14:00:00Z" },
  { id: "n5", title: "Học sinh mới đăng ký", content: "Em Thảo My vừa đăng ký vào lớp Toán Nâng Cao 12.", target_role: "teacher" as const, is_read: false, created_at: "2025-05-01T09:00:00Z" },
  { id: "n6", title: "Bảo trì Hệ thống", content: "Hệ thống sẽ bảo trì từ 2 AM - 4 AM ngày 15/05/2025. Vui lòng không làm bài kiểm tra trong thời gian này.", target_role: "all" as UserRole, is_read: false, created_at: "2025-05-07T12:00:00Z" },
];

export const MOCK_EXAM_SCORES = [
  // s1 — class c1 (Toán THPT Nâng Cao)
  { id: "e1",  student_id: "s1", class_id: "c1", exam_name: "Kiểm tra 15' – Hàm số",      score: 8.0, max_score: 10, exam_date: "2026-05-10" },
  { id: "e6",  student_id: "s1", class_id: "c1", exam_name: "Kiểm tra 1 tiết – Đạo hàm", score: 8.7, max_score: 10, exam_date: "2026-05-26" },
  { id: "e9",  student_id: "s1", class_id: "c1", exam_name: "Thi Giữa Kỳ",               score: 8.5, max_score: 10, exam_date: "2026-06-09" },
  { id: "e10", student_id: "s1", class_id: "c1", exam_name: "Kiểm tra 15' – Tích phân",   score: 9.0, max_score: 10, exam_date: "2026-06-23" },
  // s1 — class c2 (Hình Học Không Gian)
  { id: "e2",  student_id: "s1", class_id: "c2", exam_name: "Kiểm tra 15' – Vectơ",       score: 9.5, max_score: 10, exam_date: "2026-05-13" },
  { id: "e7",  student_id: "s1", class_id: "c2", exam_name: "Kiểm tra 1 tiết – Mặt phẳng",score: 9.1, max_score: 10, exam_date: "2026-06-03" },
  { id: "e8",  student_id: "s1", class_id: "c2", exam_name: "Thi Giữa Kỳ",               score: 8.8, max_score: 10, exam_date: "2026-06-17" },
  // s2 (Trần Mai Phương) — c1
  { id: "e3",  student_id: "s2", class_id: "c1", exam_name: "Kiểm tra 15' – Hàm số",      score: 7.5, max_score: 10, exam_date: "2026-05-10" },
  { id: "e11", student_id: "s2", class_id: "c1", exam_name: "Kiểm tra 1 tiết – Đạo hàm", score: 8.0, max_score: 10, exam_date: "2026-05-26" },
  { id: "e12", student_id: "s2", class_id: "c1", exam_name: "Thi Giữa Kỳ",               score: 7.9, max_score: 10, exam_date: "2026-06-09" },
  // s2 — c3
  { id: "e13", student_id: "s2", class_id: "c3", exam_name: "Kiểm tra 15' – Phương trình",score: 8.2, max_score: 10, exam_date: "2026-05-14" },
  { id: "e14", student_id: "s2", class_id: "c3", exam_name: "Kiểm tra 1 tiết – Đại số",  score: 7.8, max_score: 10, exam_date: "2026-06-04" },
  // s3 (Lê Hoàng Đức) — c3
  { id: "e4",  student_id: "s3", class_id: "c3", exam_name: "Kiểm tra 15' – Phương trình",score: 7.0, max_score: 10, exam_date: "2026-05-14" },
  { id: "e15", student_id: "s3", class_id: "c3", exam_name: "Kiểm tra 1 tiết – Đại số",  score: 7.5, max_score: 10, exam_date: "2026-06-04" },
  { id: "e16", student_id: "s3", class_id: "c3", exam_name: "Thi Giữa Kỳ",               score: 8.1, max_score: 10, exam_date: "2026-06-18" },
  // s4 (Phạm Thảo My) — c1
  { id: "e5",  student_id: "s4", class_id: "c1", exam_name: "Kiểm tra 15' – Hàm số",      score: 9.0, max_score: 10, exam_date: "2026-05-10" },
  { id: "e17", student_id: "s4", class_id: "c1", exam_name: "Kiểm tra 1 tiết – Đạo hàm", score: 9.2, max_score: 10, exam_date: "2026-05-26" },
  { id: "e18", student_id: "s4", class_id: "c1", exam_name: "Thi Giữa Kỳ",               score: 9.4, max_score: 10, exam_date: "2026-06-09" },
  { id: "e19", student_id: "s4", class_id: "c1", exam_name: "Kiểm tra 15' – Tích phân",   score: 9.1, max_score: 10, exam_date: "2026-06-23" },
];

export const ATTENDANCE_CHART_DATA = [
  { month: "Jan", present: 88, absent: 8, late: 4 },
  { month: "Feb", present: 92, absent: 5, late: 3 },
  { month: "Mar", present: 85, absent: 10, late: 5 },
  { month: "Apr", present: 90, absent: 6, late: 4 },
  { month: "May", present: 87, absent: 9, late: 4 },
];

export const REVENUE_CHART_DATA = [
  { month: "Jan", revenue: 84000000, target: 90000000 },
  { month: "Feb", revenue: 92000000, target: 90000000 },
  { month: "Mar", revenue: 78000000, target: 90000000 },
  { month: "Apr", revenue: 96000000, target: 90000000 },
  { month: "May", revenue: 89000000, target: 90000000 },
];

export const STUDENT_SCORE_DATA = [
  { subject: "Đại Số", score: 8.7 },
  { subject: "Hình Học", score: 9.1 },
  { subject: "Giải Tích", score: 8.5 },
  { subject: "Xác Suất", score: 7.9 },
];
